api = "0.5"

[buildpack]
  id = "arjun024/dependencyfile"
  name = ""
  version = "1.0.0"

[metadata]
  include-files = ["bin/build", "bin/detect", "buildpack.toml"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
